### ISSUE TITLE
Does the analyzer actually analyze anything?

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/common-lisp-analyzer#40]
I've been looking at the analyzer code for a bit, and to my untrained eyes it looks like it doesn't really analyze anything yet. Is that correct? If it doesn't, I would suggest disabling the analyzer in the track config (https://github.com/exercism/common-lisp/blob/main/config.json#L9), as that will save us some resources.

**Comment by ErikSchierboom** [comment]
No worries. If you could be so kind to disable the analyzer then please :)

**Comment by verdammelt** [comment]
I will do that tonight (Eastern US time)

**Comment by verdammelt** [comment]
Turning off the analyzer on the track for now.

(_cf._ exercism/common-lisp#761)
